import type { ReactNode } from "react";

import { cn } from "@/lib/utils";
import { ReportLetterhead } from "./ReportLetterhead";
import { ReportFooter } from "./ReportFooter";

interface MetaRow {
  label: string;
  value: string;
}

interface ReportDocumentProps {
  reportName: string;
  reportNumber: string;
  generatedAt: string;
  generatedBy: string;
  dateRangeLabel?: string;
  children: ReactNode;
  className?: string;
}

/**
 * Professional A4 (portrait) report document: letterhead + report header +
 * body + signatory footer. Rendered on-screen as an A4-proportioned sheet and
 * printed/exported via the `.report-print-area` print stylesheet in styles.css.
 */
export function ReportDocument({
  reportName,
  reportNumber,
  generatedAt,
  generatedBy,
  dateRangeLabel,
  children,
  className,
}: ReportDocumentProps) {
  const meta: MetaRow[] = [
    { label: "Report No.", value: reportNumber },
    { label: "Generated", value: generatedAt },
    ...(dateRangeLabel ? [{ label: "Date Range", value: dateRangeLabel }] : []),
    { label: "Generated By", value: generatedBy },
  ];

  return (
    <div
      className={cn(
        "report-print-area mx-auto w-full max-w-[210mm] rounded-lg border border-border bg-card p-8 text-foreground shadow-sm",
        className,
      )}
    >
      <ReportLetterhead />

      <div className="mt-5 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between">
        <div>
          <p className="text-[11px] font-semibold uppercase tracking-[0.18em] text-brand">
            Official Report
          </p>
          <h1 className="text-xl font-bold tracking-tight text-foreground">{reportName}</h1>
        </div>
        <dl className="grid grid-cols-2 gap-x-4 gap-y-0.5 text-xs sm:text-right">
          {meta.map((m) => (
            <div key={m.label} className="contents">
              <dt className="text-muted-foreground sm:text-right">{m.label}</dt>
              <dd className="font-medium text-foreground">{m.value}</dd>
            </div>
          ))}
        </dl>
      </div>

      <hr className="my-4 border-border" />

      <div className="report-body space-y-6">{children}</div>

      <ReportFooter reportNumber={reportNumber} printDate={generatedAt} />
    </div>
  );
}
