import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect, useMemo, useState } from "react";
import { Download, Loader2, Printer, Search } from "lucide-react";
import { toast } from "sonner";

import { PageHeader } from "@/components/PageHeader";
import { NoAccess } from "@/components/NoAccess";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { useAuth } from "@/lib/auth-context";
import { fetchReportHistory, REPORT_TYPE_LABELS, type ReportExportRow, type ReportType } from "@/lib/reports";
import { fetchUserNames, formatCurrency, formatDate, formatDateTime } from "@/lib/expenses";

export const Route = createFileRoute("/_authenticated/reports/export-history")({
  head: () => ({ meta: [{ title: "Export History — Motion IT BD" }] }),
  component: ExportHistoryPage,
});

function rangeLabel(row: ReportExportRow): string {
  if (!row.range_from || !row.range_to) return "Selected expenses";
  if (row.range_from === row.range_to) return formatDate(row.range_from);
  return `${formatDate(row.range_from)} – ${formatDate(row.range_to)}`;
}

function reuseLink(row: ReportExportRow, byName: string) {
  const ids =
    Array.isArray((row.filters as { ids?: unknown }).ids)
      ? ((row.filters as { ids: string[] }).ids).join(",")
      : undefined;
  return {
    to: "/reports/summary" as const,
    search: {
      type: row.report_type as ReportType,
      from: row.range_from ?? undefined,
      to: row.range_to ?? undefined,
      ids,
      rnum: row.report_number,
      gen: row.created_at,
      by: byName,
    },
  };
}

function ExportHistoryPage() {
  const { canAccessModule } = useAuth();
  const [rows, setRows] = useState<ReportExportRow[]>([]);
  const [names, setNames] = useState<Record<string, string>>({});
  const [loading, setLoading] = useState(true);
  const [q, setQ] = useState("");

  useEffect(() => {
    (async () => {
      try {
        const data = await fetchReportHistory();
        setRows(data);
        const map = await fetchUserNames(
          data.map((r) => r.generated_by).filter(Boolean) as string[],
        );
        setNames(map);
      } catch (e) {
        toast.error(e instanceof Error ? e.message : "Failed to load history.");
      } finally {
        setLoading(false);
      }
    })();
  }, []);

  const filtered = useMemo(() => {
    const term = q.trim().toLowerCase();
    if (!term) return rows;
    return rows.filter((r) =>
      [r.report_number, r.title, REPORT_TYPE_LABELS[r.report_type as ReportType] ?? r.report_type]
        .join(" ")
        .toLowerCase()
        .includes(term),
    );
  }, [rows, q]);

  if (!canAccessModule("reports")) {
    return (
      <div className="space-y-8">
        <PageHeader title="Export History" />
        <NoAccess />
      </div>
    );
  }

  return (
    <div className="space-y-8">
      <PageHeader
        title="Export History"
        description="An audit trail of every generated report. Re-print or re-export any record."
      />

      <div className="relative max-w-sm">
        <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
        <Input
          value={q}
          onChange={(e) => setQ(e.target.value)}
          placeholder="Search report number or type…"
          className="pl-9"
        />
      </div>

      <Card>
        <CardContent className="p-0">
          {loading ? (
            <div className="flex justify-center py-16">
              <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
            </div>
          ) : filtered.length === 0 ? (
            <p className="py-16 text-center text-sm text-muted-foreground">
              No reports generated yet.
            </p>
          ) : (
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Report No.</TableHead>
                  <TableHead>Type</TableHead>
                  <TableHead>Generated By</TableHead>
                  <TableHead>Generated</TableHead>
                  <TableHead>Date Range</TableHead>
                  <TableHead className="text-right">Items</TableHead>
                  <TableHead className="text-right">Total</TableHead>
                  <TableHead className="text-right">Actions</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {filtered.map((r) => {
                  const byName = r.generated_by ? names[r.generated_by] ?? "—" : "—";
                  const link = reuseLink(r, byName);
                  return (
                    <TableRow key={r.id}>
                      <TableCell className="font-medium">{r.report_number}</TableCell>
                      <TableCell>
                        <Badge variant="secondary">
                          {REPORT_TYPE_LABELS[r.report_type as ReportType] ?? r.report_type}
                        </Badge>
                      </TableCell>
                      <TableCell>{byName}</TableCell>
                      <TableCell className="whitespace-nowrap">{formatDateTime(r.created_at)}</TableCell>
                      <TableCell className="whitespace-nowrap">{rangeLabel(r)}</TableCell>
                      <TableCell className="text-right tabular-nums">{r.expense_count}</TableCell>
                      <TableCell className="text-right tabular-nums">
                        {formatCurrency(Number(r.total_amount))}
                      </TableCell>
                      <TableCell className="text-right">
                        <div className="flex justify-end gap-1">
                          <Button asChild size="sm" variant="ghost">
                            <Link to={link.to} search={link.search}>
                              <Printer className="h-3.5 w-3.5" />
                              Print
                            </Link>
                          </Button>
                          <Button asChild size="sm" variant="ghost">
                            <Link to={link.to} search={link.search}>
                              <Download className="h-3.5 w-3.5" />
                              PDF
                            </Link>
                          </Button>
                        </div>
                      </TableCell>
                    </TableRow>
                  );
                })}
              </TableBody>
            </Table>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
