import { useBranding } from "@/lib/branding-context";
import { APP_NAME } from "@/lib/modules";
import { BrandMark } from "@/components/BrandMark";
import { cn } from "@/lib/utils";

interface ReportHeaderProps {
  /** Document / report title, e.g. "Monthly Expense Summary". */
  title: string;
  /** Optional subtitle or reporting period. */
  subtitle?: string;
  /** Optional right-aligned metadata rows (e.g. date range, generated by). */
  meta?: { label: string; value: string }[];
  className?: string;
}

/**
 * Branded header for reports, print layouts, and PDF exports.
 *
 * It reads live company branding (name, logo, contact details) from the
 * BrandingProvider so every export automatically inherits the current
 * Motion IT BD brand. Drop it at the top of any report/printable view; the
 * gradient rule and colors are configured to survive printing via the
 * print-color-adjust rules in styles.css.
 */
export function ReportHeader({ title, subtitle, meta, className }: ReportHeaderProps) {
  const { company, logoUrl } = useBranding();
  const name = company?.name?.trim() || APP_NAME;

  const contacts = [company?.email, company?.mobile, company?.website].filter(Boolean) as string[];

  return (
    <header className={cn("space-y-4", className)}>
      <div className="flex items-start justify-between gap-6">
        <div className="flex items-center gap-3">
          <div className="flex h-12 w-12 shrink-0 items-center justify-center overflow-hidden rounded-lg">
            {logoUrl ? (
              <img
                src={logoUrl}
                alt={name}
                className="max-h-full max-w-full bg-muted object-contain p-1"
              />
            ) : (
              <BrandMark className="h-full w-full" title={name} />
            )}
          </div>
          <div className="min-w-0">
            <p className="truncate text-base font-semibold tracking-tight text-foreground">{name}</p>
            {company?.address && (
              <p className="truncate text-xs text-muted-foreground">{company.address}</p>
            )}
            {contacts.length > 0 && (
              <p className="truncate text-xs text-muted-foreground">{contacts.join("  ·  ")}</p>
            )}
          </div>
        </div>

        {meta && meta.length > 0 && (
          <dl className="hidden shrink-0 space-y-0.5 text-right text-xs sm:block">
            {meta.map((m) => (
              <div key={m.label} className="flex justify-end gap-2">
                <dt className="text-muted-foreground">{m.label}:</dt>
                <dd className="font-medium text-foreground">{m.value}</dd>
              </div>
            ))}
          </dl>
        )}
      </div>

      <hr className="brand-rule" />

      <div>
        <h1 className="text-xl font-semibold tracking-tight text-foreground">{title}</h1>
        {subtitle && <p className="text-sm text-muted-foreground">{subtitle}</p>}
      </div>
    </header>
  );
}