/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpdatePasswordRouteImport } from './routes/update-password'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedSystemRouteImport } from './routes/_authenticated/system'
import { Route as AuthenticatedReturnsRouteImport } from './routes/_authenticated/returns'
import { Route as AuthenticatedReadinessRouteImport } from './routes/_authenticated/readiness'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedMarketingRouteImport } from './routes/_authenticated/marketing'
import { Route as AuthenticatedLossRouteImport } from './routes/_authenticated/loss'
import { Route as AuthenticatedFixedCostsRouteImport } from './routes/_authenticated/fixed-costs'
import { Route as AuthenticatedDamagesRouteImport } from './routes/_authenticated/damages'
import { Route as AuthenticatedBackupRouteImport } from './routes/_authenticated/backup'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings.index'
import { Route as AuthenticatedReturnsIndexRouteImport } from './routes/_authenticated/returns.index'
import { Route as AuthenticatedMarketingIndexRouteImport } from './routes/_authenticated/marketing.index'
import { Route as AuthenticatedFixedCostsIndexRouteImport } from './routes/_authenticated/fixed-costs.index'
import { Route as AuthenticatedExpensesIndexRouteImport } from './routes/_authenticated/expenses.index'
import { Route as AuthenticatedDamagesIndexRouteImport } from './routes/_authenticated/damages.index'
import { Route as AuthenticatedSettingsSignatoriesRouteImport } from './routes/_authenticated/settings.signatories'
import { Route as AuthenticatedSettingsPreferencesRouteImport } from './routes/_authenticated/settings.preferences'
import { Route as AuthenticatedSettingsPermissionsRouteImport } from './routes/_authenticated/settings.permissions'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings.notifications'
import { Route as AuthenticatedSettingsMarketingRouteImport } from './routes/_authenticated/settings.marketing'
import { Route as AuthenticatedSettingsLossRouteImport } from './routes/_authenticated/settings.loss'
import { Route as AuthenticatedSettingsFixedCostsRouteImport } from './routes/_authenticated/settings.fixed-costs'
import { Route as AuthenticatedSettingsCompanyRouteImport } from './routes/_authenticated/settings.company'
import { Route as AuthenticatedReturnsReportsRouteImport } from './routes/_authenticated/returns.reports'
import { Route as AuthenticatedReturnsPendingRouteImport } from './routes/_authenticated/returns.pending'
import { Route as AuthenticatedReturnsAddRouteImport } from './routes/_authenticated/returns.add'
import { Route as AuthenticatedReturnsIdRouteImport } from './routes/_authenticated/returns.$id'
import { Route as AuthenticatedReportsSummaryRouteImport } from './routes/_authenticated/reports.summary'
import { Route as AuthenticatedReportsExportHistoryRouteImport } from './routes/_authenticated/reports.export-history'
import { Route as AuthenticatedReportsDetailedRouteImport } from './routes/_authenticated/reports.detailed'
import { Route as AuthenticatedMarketingReportsRouteImport } from './routes/_authenticated/marketing.reports'
import { Route as AuthenticatedMarketingAddRouteImport } from './routes/_authenticated/marketing.add'
import { Route as AuthenticatedFixedCostsReportsRouteImport } from './routes/_authenticated/fixed-costs.reports'
import { Route as AuthenticatedExpensesRecycleBinRouteImport } from './routes/_authenticated/expenses.recycle-bin'
import { Route as AuthenticatedExpensesPendingRouteImport } from './routes/_authenticated/expenses.pending'
import { Route as AuthenticatedExpensesCategoriesRouteImport } from './routes/_authenticated/expenses.categories'
import { Route as AuthenticatedExpensesAddRouteImport } from './routes/_authenticated/expenses.add'
import { Route as AuthenticatedExpensesIdRouteImport } from './routes/_authenticated/expenses.$id'
import { Route as AuthenticatedDamagesReportsRouteImport } from './routes/_authenticated/damages.reports'
import { Route as AuthenticatedDamagesPendingRouteImport } from './routes/_authenticated/damages.pending'
import { Route as AuthenticatedDamagesAddRouteImport } from './routes/_authenticated/damages.add'
import { Route as AuthenticatedDamagesIdRouteImport } from './routes/_authenticated/damages.$id'
import { Route as AuthenticatedReturnsReasonIdRouteImport } from './routes/_authenticated/returns.reason.$id'
import { Route as AuthenticatedMarketingPlatformIdRouteImport } from './routes/_authenticated/marketing.platform.$id'
import { Route as AuthenticatedDashboardSubcategoryIdRouteImport } from './routes/_authenticated/dashboard.subcategory.$id'
import { Route as AuthenticatedDashboardCategoryIdRouteImport } from './routes/_authenticated/dashboard.category.$id'
import { Route as AuthenticatedDamagesTypeIdRouteImport } from './routes/_authenticated/damages.type.$id'

const UpdatePasswordRoute = UpdatePasswordRouteImport.update({
  id: '/update-password',
  path: '/update-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSystemRoute = AuthenticatedSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReturnsRoute = AuthenticatedReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReadinessRoute = AuthenticatedReadinessRouteImport.update({
  id: '/readiness',
  path: '/readiness',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMarketingRoute = AuthenticatedMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLossRoute = AuthenticatedLossRouteImport.update({
  id: '/loss',
  path: '/loss',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFixedCostsRoute = AuthenticatedFixedCostsRouteImport.update({
  id: '/fixed-costs',
  path: '/fixed-costs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDamagesRoute = AuthenticatedDamagesRouteImport.update({
  id: '/damages',
  path: '/damages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBackupRoute = AuthenticatedBackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReturnsIndexRoute =
  AuthenticatedReturnsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedReturnsRoute,
  } as any)
const AuthenticatedMarketingIndexRoute =
  AuthenticatedMarketingIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMarketingRoute,
  } as any)
const AuthenticatedFixedCostsIndexRoute =
  AuthenticatedFixedCostsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedFixedCostsRoute,
  } as any)
const AuthenticatedExpensesIndexRoute =
  AuthenticatedExpensesIndexRouteImport.update({
    id: '/expenses/',
    path: '/expenses/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDamagesIndexRoute =
  AuthenticatedDamagesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDamagesRoute,
  } as any)
const AuthenticatedSettingsSignatoriesRoute =
  AuthenticatedSettingsSignatoriesRouteImport.update({
    id: '/settings/signatories',
    path: '/settings/signatories',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsPreferencesRoute =
  AuthenticatedSettingsPreferencesRouteImport.update({
    id: '/settings/preferences',
    path: '/settings/preferences',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsPermissionsRoute =
  AuthenticatedSettingsPermissionsRouteImport.update({
    id: '/settings/permissions',
    path: '/settings/permissions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/settings/notifications',
    path: '/settings/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsMarketingRoute =
  AuthenticatedSettingsMarketingRouteImport.update({
    id: '/settings/marketing',
    path: '/settings/marketing',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsLossRoute =
  AuthenticatedSettingsLossRouteImport.update({
    id: '/settings/loss',
    path: '/settings/loss',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsFixedCostsRoute =
  AuthenticatedSettingsFixedCostsRouteImport.update({
    id: '/settings/fixed-costs',
    path: '/settings/fixed-costs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsCompanyRoute =
  AuthenticatedSettingsCompanyRouteImport.update({
    id: '/settings/company',
    path: '/settings/company',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReturnsReportsRoute =
  AuthenticatedReturnsReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedReturnsRoute,
  } as any)
const AuthenticatedReturnsPendingRoute =
  AuthenticatedReturnsPendingRouteImport.update({
    id: '/pending',
    path: '/pending',
    getParentRoute: () => AuthenticatedReturnsRoute,
  } as any)
const AuthenticatedReturnsAddRoute = AuthenticatedReturnsAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => AuthenticatedReturnsRoute,
} as any)
const AuthenticatedReturnsIdRoute = AuthenticatedReturnsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedReturnsRoute,
} as any)
const AuthenticatedReportsSummaryRoute =
  AuthenticatedReportsSummaryRouteImport.update({
    id: '/reports/summary',
    path: '/reports/summary',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsExportHistoryRoute =
  AuthenticatedReportsExportHistoryRouteImport.update({
    id: '/reports/export-history',
    path: '/reports/export-history',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsDetailedRoute =
  AuthenticatedReportsDetailedRouteImport.update({
    id: '/reports/detailed',
    path: '/reports/detailed',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMarketingReportsRoute =
  AuthenticatedMarketingReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedMarketingRoute,
  } as any)
const AuthenticatedMarketingAddRoute =
  AuthenticatedMarketingAddRouteImport.update({
    id: '/add',
    path: '/add',
    getParentRoute: () => AuthenticatedMarketingRoute,
  } as any)
const AuthenticatedFixedCostsReportsRoute =
  AuthenticatedFixedCostsReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedFixedCostsRoute,
  } as any)
const AuthenticatedExpensesRecycleBinRoute =
  AuthenticatedExpensesRecycleBinRouteImport.update({
    id: '/expenses/recycle-bin',
    path: '/expenses/recycle-bin',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExpensesPendingRoute =
  AuthenticatedExpensesPendingRouteImport.update({
    id: '/expenses/pending',
    path: '/expenses/pending',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExpensesCategoriesRoute =
  AuthenticatedExpensesCategoriesRouteImport.update({
    id: '/expenses/categories',
    path: '/expenses/categories',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExpensesAddRoute =
  AuthenticatedExpensesAddRouteImport.update({
    id: '/expenses/add',
    path: '/expenses/add',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExpensesIdRoute = AuthenticatedExpensesIdRouteImport.update({
  id: '/expenses/$id',
  path: '/expenses/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDamagesReportsRoute =
  AuthenticatedDamagesReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedDamagesRoute,
  } as any)
const AuthenticatedDamagesPendingRoute =
  AuthenticatedDamagesPendingRouteImport.update({
    id: '/pending',
    path: '/pending',
    getParentRoute: () => AuthenticatedDamagesRoute,
  } as any)
const AuthenticatedDamagesAddRoute = AuthenticatedDamagesAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => AuthenticatedDamagesRoute,
} as any)
const AuthenticatedDamagesIdRoute = AuthenticatedDamagesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedDamagesRoute,
} as any)
const AuthenticatedReturnsReasonIdRoute =
  AuthenticatedReturnsReasonIdRouteImport.update({
    id: '/reason/$id',
    path: '/reason/$id',
    getParentRoute: () => AuthenticatedReturnsRoute,
  } as any)
const AuthenticatedMarketingPlatformIdRoute =
  AuthenticatedMarketingPlatformIdRouteImport.update({
    id: '/platform/$id',
    path: '/platform/$id',
    getParentRoute: () => AuthenticatedMarketingRoute,
  } as any)
const AuthenticatedDashboardSubcategoryIdRoute =
  AuthenticatedDashboardSubcategoryIdRouteImport.update({
    id: '/dashboard/subcategory/$id',
    path: '/dashboard/subcategory/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardCategoryIdRoute =
  AuthenticatedDashboardCategoryIdRouteImport.update({
    id: '/dashboard/category/$id',
    path: '/dashboard/category/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDamagesTypeIdRoute =
  AuthenticatedDamagesTypeIdRouteImport.update({
    id: '/type/$id',
    path: '/type/$id',
    getParentRoute: () => AuthenticatedDamagesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/update-password': typeof UpdatePasswordRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/backup': typeof AuthenticatedBackupRoute
  '/damages': typeof AuthenticatedDamagesRouteWithChildren
  '/fixed-costs': typeof AuthenticatedFixedCostsRouteWithChildren
  '/loss': typeof AuthenticatedLossRoute
  '/marketing': typeof AuthenticatedMarketingRouteWithChildren
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/readiness': typeof AuthenticatedReadinessRoute
  '/returns': typeof AuthenticatedReturnsRouteWithChildren
  '/system': typeof AuthenticatedSystemRoute
  '/users': typeof AuthenticatedUsersRoute
  '/damages/$id': typeof AuthenticatedDamagesIdRoute
  '/damages/add': typeof AuthenticatedDamagesAddRoute
  '/damages/pending': typeof AuthenticatedDamagesPendingRoute
  '/damages/reports': typeof AuthenticatedDamagesReportsRoute
  '/expenses/$id': typeof AuthenticatedExpensesIdRoute
  '/expenses/add': typeof AuthenticatedExpensesAddRoute
  '/expenses/categories': typeof AuthenticatedExpensesCategoriesRoute
  '/expenses/pending': typeof AuthenticatedExpensesPendingRoute
  '/expenses/recycle-bin': typeof AuthenticatedExpensesRecycleBinRoute
  '/fixed-costs/reports': typeof AuthenticatedFixedCostsReportsRoute
  '/marketing/add': typeof AuthenticatedMarketingAddRoute
  '/marketing/reports': typeof AuthenticatedMarketingReportsRoute
  '/reports/detailed': typeof AuthenticatedReportsDetailedRoute
  '/reports/export-history': typeof AuthenticatedReportsExportHistoryRoute
  '/reports/summary': typeof AuthenticatedReportsSummaryRoute
  '/returns/$id': typeof AuthenticatedReturnsIdRoute
  '/returns/add': typeof AuthenticatedReturnsAddRoute
  '/returns/pending': typeof AuthenticatedReturnsPendingRoute
  '/returns/reports': typeof AuthenticatedReturnsReportsRoute
  '/settings/company': typeof AuthenticatedSettingsCompanyRoute
  '/settings/fixed-costs': typeof AuthenticatedSettingsFixedCostsRoute
  '/settings/loss': typeof AuthenticatedSettingsLossRoute
  '/settings/marketing': typeof AuthenticatedSettingsMarketingRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/permissions': typeof AuthenticatedSettingsPermissionsRoute
  '/settings/preferences': typeof AuthenticatedSettingsPreferencesRoute
  '/settings/signatories': typeof AuthenticatedSettingsSignatoriesRoute
  '/damages/': typeof AuthenticatedDamagesIndexRoute
  '/expenses/': typeof AuthenticatedExpensesIndexRoute
  '/fixed-costs/': typeof AuthenticatedFixedCostsIndexRoute
  '/marketing/': typeof AuthenticatedMarketingIndexRoute
  '/returns/': typeof AuthenticatedReturnsIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/damages/type/$id': typeof AuthenticatedDamagesTypeIdRoute
  '/dashboard/category/$id': typeof AuthenticatedDashboardCategoryIdRoute
  '/dashboard/subcategory/$id': typeof AuthenticatedDashboardSubcategoryIdRoute
  '/marketing/platform/$id': typeof AuthenticatedMarketingPlatformIdRoute
  '/returns/reason/$id': typeof AuthenticatedReturnsReasonIdRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/update-password': typeof UpdatePasswordRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/backup': typeof AuthenticatedBackupRoute
  '/loss': typeof AuthenticatedLossRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/readiness': typeof AuthenticatedReadinessRoute
  '/system': typeof AuthenticatedSystemRoute
  '/users': typeof AuthenticatedUsersRoute
  '/': typeof AuthenticatedIndexRoute
  '/damages/$id': typeof AuthenticatedDamagesIdRoute
  '/damages/add': typeof AuthenticatedDamagesAddRoute
  '/damages/pending': typeof AuthenticatedDamagesPendingRoute
  '/damages/reports': typeof AuthenticatedDamagesReportsRoute
  '/expenses/$id': typeof AuthenticatedExpensesIdRoute
  '/expenses/add': typeof AuthenticatedExpensesAddRoute
  '/expenses/categories': typeof AuthenticatedExpensesCategoriesRoute
  '/expenses/pending': typeof AuthenticatedExpensesPendingRoute
  '/expenses/recycle-bin': typeof AuthenticatedExpensesRecycleBinRoute
  '/fixed-costs/reports': typeof AuthenticatedFixedCostsReportsRoute
  '/marketing/add': typeof AuthenticatedMarketingAddRoute
  '/marketing/reports': typeof AuthenticatedMarketingReportsRoute
  '/reports/detailed': typeof AuthenticatedReportsDetailedRoute
  '/reports/export-history': typeof AuthenticatedReportsExportHistoryRoute
  '/reports/summary': typeof AuthenticatedReportsSummaryRoute
  '/returns/$id': typeof AuthenticatedReturnsIdRoute
  '/returns/add': typeof AuthenticatedReturnsAddRoute
  '/returns/pending': typeof AuthenticatedReturnsPendingRoute
  '/returns/reports': typeof AuthenticatedReturnsReportsRoute
  '/settings/company': typeof AuthenticatedSettingsCompanyRoute
  '/settings/fixed-costs': typeof AuthenticatedSettingsFixedCostsRoute
  '/settings/loss': typeof AuthenticatedSettingsLossRoute
  '/settings/marketing': typeof AuthenticatedSettingsMarketingRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/permissions': typeof AuthenticatedSettingsPermissionsRoute
  '/settings/preferences': typeof AuthenticatedSettingsPreferencesRoute
  '/settings/signatories': typeof AuthenticatedSettingsSignatoriesRoute
  '/damages': typeof AuthenticatedDamagesIndexRoute
  '/expenses': typeof AuthenticatedExpensesIndexRoute
  '/fixed-costs': typeof AuthenticatedFixedCostsIndexRoute
  '/marketing': typeof AuthenticatedMarketingIndexRoute
  '/returns': typeof AuthenticatedReturnsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/damages/type/$id': typeof AuthenticatedDamagesTypeIdRoute
  '/dashboard/category/$id': typeof AuthenticatedDashboardCategoryIdRoute
  '/dashboard/subcategory/$id': typeof AuthenticatedDashboardSubcategoryIdRoute
  '/marketing/platform/$id': typeof AuthenticatedMarketingPlatformIdRoute
  '/returns/reason/$id': typeof AuthenticatedReturnsReasonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/update-password': typeof UpdatePasswordRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/backup': typeof AuthenticatedBackupRoute
  '/_authenticated/damages': typeof AuthenticatedDamagesRouteWithChildren
  '/_authenticated/fixed-costs': typeof AuthenticatedFixedCostsRouteWithChildren
  '/_authenticated/loss': typeof AuthenticatedLossRoute
  '/_authenticated/marketing': typeof AuthenticatedMarketingRouteWithChildren
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/readiness': typeof AuthenticatedReadinessRoute
  '/_authenticated/returns': typeof AuthenticatedReturnsRouteWithChildren
  '/_authenticated/system': typeof AuthenticatedSystemRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/damages/$id': typeof AuthenticatedDamagesIdRoute
  '/_authenticated/damages/add': typeof AuthenticatedDamagesAddRoute
  '/_authenticated/damages/pending': typeof AuthenticatedDamagesPendingRoute
  '/_authenticated/damages/reports': typeof AuthenticatedDamagesReportsRoute
  '/_authenticated/expenses/$id': typeof AuthenticatedExpensesIdRoute
  '/_authenticated/expenses/add': typeof AuthenticatedExpensesAddRoute
  '/_authenticated/expenses/categories': typeof AuthenticatedExpensesCategoriesRoute
  '/_authenticated/expenses/pending': typeof AuthenticatedExpensesPendingRoute
  '/_authenticated/expenses/recycle-bin': typeof AuthenticatedExpensesRecycleBinRoute
  '/_authenticated/fixed-costs/reports': typeof AuthenticatedFixedCostsReportsRoute
  '/_authenticated/marketing/add': typeof AuthenticatedMarketingAddRoute
  '/_authenticated/marketing/reports': typeof AuthenticatedMarketingReportsRoute
  '/_authenticated/reports/detailed': typeof AuthenticatedReportsDetailedRoute
  '/_authenticated/reports/export-history': typeof AuthenticatedReportsExportHistoryRoute
  '/_authenticated/reports/summary': typeof AuthenticatedReportsSummaryRoute
  '/_authenticated/returns/$id': typeof AuthenticatedReturnsIdRoute
  '/_authenticated/returns/add': typeof AuthenticatedReturnsAddRoute
  '/_authenticated/returns/pending': typeof AuthenticatedReturnsPendingRoute
  '/_authenticated/returns/reports': typeof AuthenticatedReturnsReportsRoute
  '/_authenticated/settings/company': typeof AuthenticatedSettingsCompanyRoute
  '/_authenticated/settings/fixed-costs': typeof AuthenticatedSettingsFixedCostsRoute
  '/_authenticated/settings/loss': typeof AuthenticatedSettingsLossRoute
  '/_authenticated/settings/marketing': typeof AuthenticatedSettingsMarketingRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/settings/permissions': typeof AuthenticatedSettingsPermissionsRoute
  '/_authenticated/settings/preferences': typeof AuthenticatedSettingsPreferencesRoute
  '/_authenticated/settings/signatories': typeof AuthenticatedSettingsSignatoriesRoute
  '/_authenticated/damages/': typeof AuthenticatedDamagesIndexRoute
  '/_authenticated/expenses/': typeof AuthenticatedExpensesIndexRoute
  '/_authenticated/fixed-costs/': typeof AuthenticatedFixedCostsIndexRoute
  '/_authenticated/marketing/': typeof AuthenticatedMarketingIndexRoute
  '/_authenticated/returns/': typeof AuthenticatedReturnsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/damages/type/$id': typeof AuthenticatedDamagesTypeIdRoute
  '/_authenticated/dashboard/category/$id': typeof AuthenticatedDashboardCategoryIdRoute
  '/_authenticated/dashboard/subcategory/$id': typeof AuthenticatedDashboardSubcategoryIdRoute
  '/_authenticated/marketing/platform/$id': typeof AuthenticatedMarketingPlatformIdRoute
  '/_authenticated/returns/reason/$id': typeof AuthenticatedReturnsReasonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/update-password'
    | '/audit'
    | '/backup'
    | '/damages'
    | '/fixed-costs'
    | '/loss'
    | '/marketing'
    | '/notifications'
    | '/profile'
    | '/readiness'
    | '/returns'
    | '/system'
    | '/users'
    | '/damages/$id'
    | '/damages/add'
    | '/damages/pending'
    | '/damages/reports'
    | '/expenses/$id'
    | '/expenses/add'
    | '/expenses/categories'
    | '/expenses/pending'
    | '/expenses/recycle-bin'
    | '/fixed-costs/reports'
    | '/marketing/add'
    | '/marketing/reports'
    | '/reports/detailed'
    | '/reports/export-history'
    | '/reports/summary'
    | '/returns/$id'
    | '/returns/add'
    | '/returns/pending'
    | '/returns/reports'
    | '/settings/company'
    | '/settings/fixed-costs'
    | '/settings/loss'
    | '/settings/marketing'
    | '/settings/notifications'
    | '/settings/permissions'
    | '/settings/preferences'
    | '/settings/signatories'
    | '/damages/'
    | '/expenses/'
    | '/fixed-costs/'
    | '/marketing/'
    | '/returns/'
    | '/settings/'
    | '/damages/type/$id'
    | '/dashboard/category/$id'
    | '/dashboard/subcategory/$id'
    | '/marketing/platform/$id'
    | '/returns/reason/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/reset-password'
    | '/update-password'
    | '/audit'
    | '/backup'
    | '/loss'
    | '/notifications'
    | '/profile'
    | '/readiness'
    | '/system'
    | '/users'
    | '/'
    | '/damages/$id'
    | '/damages/add'
    | '/damages/pending'
    | '/damages/reports'
    | '/expenses/$id'
    | '/expenses/add'
    | '/expenses/categories'
    | '/expenses/pending'
    | '/expenses/recycle-bin'
    | '/fixed-costs/reports'
    | '/marketing/add'
    | '/marketing/reports'
    | '/reports/detailed'
    | '/reports/export-history'
    | '/reports/summary'
    | '/returns/$id'
    | '/returns/add'
    | '/returns/pending'
    | '/returns/reports'
    | '/settings/company'
    | '/settings/fixed-costs'
    | '/settings/loss'
    | '/settings/marketing'
    | '/settings/notifications'
    | '/settings/permissions'
    | '/settings/preferences'
    | '/settings/signatories'
    | '/damages'
    | '/expenses'
    | '/fixed-costs'
    | '/marketing'
    | '/returns'
    | '/settings'
    | '/damages/type/$id'
    | '/dashboard/category/$id'
    | '/dashboard/subcategory/$id'
    | '/marketing/platform/$id'
    | '/returns/reason/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/update-password'
    | '/_authenticated/audit'
    | '/_authenticated/backup'
    | '/_authenticated/damages'
    | '/_authenticated/fixed-costs'
    | '/_authenticated/loss'
    | '/_authenticated/marketing'
    | '/_authenticated/notifications'
    | '/_authenticated/profile'
    | '/_authenticated/readiness'
    | '/_authenticated/returns'
    | '/_authenticated/system'
    | '/_authenticated/users'
    | '/_authenticated/'
    | '/_authenticated/damages/$id'
    | '/_authenticated/damages/add'
    | '/_authenticated/damages/pending'
    | '/_authenticated/damages/reports'
    | '/_authenticated/expenses/$id'
    | '/_authenticated/expenses/add'
    | '/_authenticated/expenses/categories'
    | '/_authenticated/expenses/pending'
    | '/_authenticated/expenses/recycle-bin'
    | '/_authenticated/fixed-costs/reports'
    | '/_authenticated/marketing/add'
    | '/_authenticated/marketing/reports'
    | '/_authenticated/reports/detailed'
    | '/_authenticated/reports/export-history'
    | '/_authenticated/reports/summary'
    | '/_authenticated/returns/$id'
    | '/_authenticated/returns/add'
    | '/_authenticated/returns/pending'
    | '/_authenticated/returns/reports'
    | '/_authenticated/settings/company'
    | '/_authenticated/settings/fixed-costs'
    | '/_authenticated/settings/loss'
    | '/_authenticated/settings/marketing'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/settings/permissions'
    | '/_authenticated/settings/preferences'
    | '/_authenticated/settings/signatories'
    | '/_authenticated/damages/'
    | '/_authenticated/expenses/'
    | '/_authenticated/fixed-costs/'
    | '/_authenticated/marketing/'
    | '/_authenticated/returns/'
    | '/_authenticated/settings/'
    | '/_authenticated/damages/type/$id'
    | '/_authenticated/dashboard/category/$id'
    | '/_authenticated/dashboard/subcategory/$id'
    | '/_authenticated/marketing/platform/$id'
    | '/_authenticated/returns/reason/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  UpdatePasswordRoute: typeof UpdatePasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/update-password': {
      id: '/update-password'
      path: '/update-password'
      fullPath: '/update-password'
      preLoaderRoute: typeof UpdatePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system': {
      id: '/_authenticated/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof AuthenticatedSystemRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/returns': {
      id: '/_authenticated/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof AuthenticatedReturnsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/readiness': {
      id: '/_authenticated/readiness'
      path: '/readiness'
      fullPath: '/readiness'
      preLoaderRoute: typeof AuthenticatedReadinessRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketing': {
      id: '/_authenticated/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof AuthenticatedMarketingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/loss': {
      id: '/_authenticated/loss'
      path: '/loss'
      fullPath: '/loss'
      preLoaderRoute: typeof AuthenticatedLossRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fixed-costs': {
      id: '/_authenticated/fixed-costs'
      path: '/fixed-costs'
      fullPath: '/fixed-costs'
      preLoaderRoute: typeof AuthenticatedFixedCostsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/damages': {
      id: '/_authenticated/damages'
      path: '/damages'
      fullPath: '/damages'
      preLoaderRoute: typeof AuthenticatedDamagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/backup': {
      id: '/_authenticated/backup'
      path: '/backup'
      fullPath: '/backup'
      preLoaderRoute: typeof AuthenticatedBackupRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/returns/': {
      id: '/_authenticated/returns/'
      path: '/'
      fullPath: '/returns/'
      preLoaderRoute: typeof AuthenticatedReturnsIndexRouteImport
      parentRoute: typeof AuthenticatedReturnsRoute
    }
    '/_authenticated/marketing/': {
      id: '/_authenticated/marketing/'
      path: '/'
      fullPath: '/marketing/'
      preLoaderRoute: typeof AuthenticatedMarketingIndexRouteImport
      parentRoute: typeof AuthenticatedMarketingRoute
    }
    '/_authenticated/fixed-costs/': {
      id: '/_authenticated/fixed-costs/'
      path: '/'
      fullPath: '/fixed-costs/'
      preLoaderRoute: typeof AuthenticatedFixedCostsIndexRouteImport
      parentRoute: typeof AuthenticatedFixedCostsRoute
    }
    '/_authenticated/expenses/': {
      id: '/_authenticated/expenses/'
      path: '/expenses'
      fullPath: '/expenses/'
      preLoaderRoute: typeof AuthenticatedExpensesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/damages/': {
      id: '/_authenticated/damages/'
      path: '/'
      fullPath: '/damages/'
      preLoaderRoute: typeof AuthenticatedDamagesIndexRouteImport
      parentRoute: typeof AuthenticatedDamagesRoute
    }
    '/_authenticated/settings/signatories': {
      id: '/_authenticated/settings/signatories'
      path: '/settings/signatories'
      fullPath: '/settings/signatories'
      preLoaderRoute: typeof AuthenticatedSettingsSignatoriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/preferences': {
      id: '/_authenticated/settings/preferences'
      path: '/settings/preferences'
      fullPath: '/settings/preferences'
      preLoaderRoute: typeof AuthenticatedSettingsPreferencesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/permissions': {
      id: '/_authenticated/settings/permissions'
      path: '/settings/permissions'
      fullPath: '/settings/permissions'
      preLoaderRoute: typeof AuthenticatedSettingsPermissionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/marketing': {
      id: '/_authenticated/settings/marketing'
      path: '/settings/marketing'
      fullPath: '/settings/marketing'
      preLoaderRoute: typeof AuthenticatedSettingsMarketingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/loss': {
      id: '/_authenticated/settings/loss'
      path: '/settings/loss'
      fullPath: '/settings/loss'
      preLoaderRoute: typeof AuthenticatedSettingsLossRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/fixed-costs': {
      id: '/_authenticated/settings/fixed-costs'
      path: '/settings/fixed-costs'
      fullPath: '/settings/fixed-costs'
      preLoaderRoute: typeof AuthenticatedSettingsFixedCostsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/company': {
      id: '/_authenticated/settings/company'
      path: '/settings/company'
      fullPath: '/settings/company'
      preLoaderRoute: typeof AuthenticatedSettingsCompanyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/returns/reports': {
      id: '/_authenticated/returns/reports'
      path: '/reports'
      fullPath: '/returns/reports'
      preLoaderRoute: typeof AuthenticatedReturnsReportsRouteImport
      parentRoute: typeof AuthenticatedReturnsRoute
    }
    '/_authenticated/returns/pending': {
      id: '/_authenticated/returns/pending'
      path: '/pending'
      fullPath: '/returns/pending'
      preLoaderRoute: typeof AuthenticatedReturnsPendingRouteImport
      parentRoute: typeof AuthenticatedReturnsRoute
    }
    '/_authenticated/returns/add': {
      id: '/_authenticated/returns/add'
      path: '/add'
      fullPath: '/returns/add'
      preLoaderRoute: typeof AuthenticatedReturnsAddRouteImport
      parentRoute: typeof AuthenticatedReturnsRoute
    }
    '/_authenticated/returns/$id': {
      id: '/_authenticated/returns/$id'
      path: '/$id'
      fullPath: '/returns/$id'
      preLoaderRoute: typeof AuthenticatedReturnsIdRouteImport
      parentRoute: typeof AuthenticatedReturnsRoute
    }
    '/_authenticated/reports/summary': {
      id: '/_authenticated/reports/summary'
      path: '/reports/summary'
      fullPath: '/reports/summary'
      preLoaderRoute: typeof AuthenticatedReportsSummaryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/export-history': {
      id: '/_authenticated/reports/export-history'
      path: '/reports/export-history'
      fullPath: '/reports/export-history'
      preLoaderRoute: typeof AuthenticatedReportsExportHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/detailed': {
      id: '/_authenticated/reports/detailed'
      path: '/reports/detailed'
      fullPath: '/reports/detailed'
      preLoaderRoute: typeof AuthenticatedReportsDetailedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketing/reports': {
      id: '/_authenticated/marketing/reports'
      path: '/reports'
      fullPath: '/marketing/reports'
      preLoaderRoute: typeof AuthenticatedMarketingReportsRouteImport
      parentRoute: typeof AuthenticatedMarketingRoute
    }
    '/_authenticated/marketing/add': {
      id: '/_authenticated/marketing/add'
      path: '/add'
      fullPath: '/marketing/add'
      preLoaderRoute: typeof AuthenticatedMarketingAddRouteImport
      parentRoute: typeof AuthenticatedMarketingRoute
    }
    '/_authenticated/fixed-costs/reports': {
      id: '/_authenticated/fixed-costs/reports'
      path: '/reports'
      fullPath: '/fixed-costs/reports'
      preLoaderRoute: typeof AuthenticatedFixedCostsReportsRouteImport
      parentRoute: typeof AuthenticatedFixedCostsRoute
    }
    '/_authenticated/expenses/recycle-bin': {
      id: '/_authenticated/expenses/recycle-bin'
      path: '/expenses/recycle-bin'
      fullPath: '/expenses/recycle-bin'
      preLoaderRoute: typeof AuthenticatedExpensesRecycleBinRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/expenses/pending': {
      id: '/_authenticated/expenses/pending'
      path: '/expenses/pending'
      fullPath: '/expenses/pending'
      preLoaderRoute: typeof AuthenticatedExpensesPendingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/expenses/categories': {
      id: '/_authenticated/expenses/categories'
      path: '/expenses/categories'
      fullPath: '/expenses/categories'
      preLoaderRoute: typeof AuthenticatedExpensesCategoriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/expenses/add': {
      id: '/_authenticated/expenses/add'
      path: '/expenses/add'
      fullPath: '/expenses/add'
      preLoaderRoute: typeof AuthenticatedExpensesAddRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/expenses/$id': {
      id: '/_authenticated/expenses/$id'
      path: '/expenses/$id'
      fullPath: '/expenses/$id'
      preLoaderRoute: typeof AuthenticatedExpensesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/damages/reports': {
      id: '/_authenticated/damages/reports'
      path: '/reports'
      fullPath: '/damages/reports'
      preLoaderRoute: typeof AuthenticatedDamagesReportsRouteImport
      parentRoute: typeof AuthenticatedDamagesRoute
    }
    '/_authenticated/damages/pending': {
      id: '/_authenticated/damages/pending'
      path: '/pending'
      fullPath: '/damages/pending'
      preLoaderRoute: typeof AuthenticatedDamagesPendingRouteImport
      parentRoute: typeof AuthenticatedDamagesRoute
    }
    '/_authenticated/damages/add': {
      id: '/_authenticated/damages/add'
      path: '/add'
      fullPath: '/damages/add'
      preLoaderRoute: typeof AuthenticatedDamagesAddRouteImport
      parentRoute: typeof AuthenticatedDamagesRoute
    }
    '/_authenticated/damages/$id': {
      id: '/_authenticated/damages/$id'
      path: '/$id'
      fullPath: '/damages/$id'
      preLoaderRoute: typeof AuthenticatedDamagesIdRouteImport
      parentRoute: typeof AuthenticatedDamagesRoute
    }
    '/_authenticated/returns/reason/$id': {
      id: '/_authenticated/returns/reason/$id'
      path: '/reason/$id'
      fullPath: '/returns/reason/$id'
      preLoaderRoute: typeof AuthenticatedReturnsReasonIdRouteImport
      parentRoute: typeof AuthenticatedReturnsRoute
    }
    '/_authenticated/marketing/platform/$id': {
      id: '/_authenticated/marketing/platform/$id'
      path: '/platform/$id'
      fullPath: '/marketing/platform/$id'
      preLoaderRoute: typeof AuthenticatedMarketingPlatformIdRouteImport
      parentRoute: typeof AuthenticatedMarketingRoute
    }
    '/_authenticated/dashboard/subcategory/$id': {
      id: '/_authenticated/dashboard/subcategory/$id'
      path: '/dashboard/subcategory/$id'
      fullPath: '/dashboard/subcategory/$id'
      preLoaderRoute: typeof AuthenticatedDashboardSubcategoryIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/category/$id': {
      id: '/_authenticated/dashboard/category/$id'
      path: '/dashboard/category/$id'
      fullPath: '/dashboard/category/$id'
      preLoaderRoute: typeof AuthenticatedDashboardCategoryIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/damages/type/$id': {
      id: '/_authenticated/damages/type/$id'
      path: '/type/$id'
      fullPath: '/damages/type/$id'
      preLoaderRoute: typeof AuthenticatedDamagesTypeIdRouteImport
      parentRoute: typeof AuthenticatedDamagesRoute
    }
  }
}

interface AuthenticatedDamagesRouteChildren {
  AuthenticatedDamagesIdRoute: typeof AuthenticatedDamagesIdRoute
  AuthenticatedDamagesAddRoute: typeof AuthenticatedDamagesAddRoute
  AuthenticatedDamagesPendingRoute: typeof AuthenticatedDamagesPendingRoute
  AuthenticatedDamagesReportsRoute: typeof AuthenticatedDamagesReportsRoute
  AuthenticatedDamagesIndexRoute: typeof AuthenticatedDamagesIndexRoute
  AuthenticatedDamagesTypeIdRoute: typeof AuthenticatedDamagesTypeIdRoute
}

const AuthenticatedDamagesRouteChildren: AuthenticatedDamagesRouteChildren = {
  AuthenticatedDamagesIdRoute: AuthenticatedDamagesIdRoute,
  AuthenticatedDamagesAddRoute: AuthenticatedDamagesAddRoute,
  AuthenticatedDamagesPendingRoute: AuthenticatedDamagesPendingRoute,
  AuthenticatedDamagesReportsRoute: AuthenticatedDamagesReportsRoute,
  AuthenticatedDamagesIndexRoute: AuthenticatedDamagesIndexRoute,
  AuthenticatedDamagesTypeIdRoute: AuthenticatedDamagesTypeIdRoute,
}

const AuthenticatedDamagesRouteWithChildren =
  AuthenticatedDamagesRoute._addFileChildren(AuthenticatedDamagesRouteChildren)

interface AuthenticatedFixedCostsRouteChildren {
  AuthenticatedFixedCostsReportsRoute: typeof AuthenticatedFixedCostsReportsRoute
  AuthenticatedFixedCostsIndexRoute: typeof AuthenticatedFixedCostsIndexRoute
}

const AuthenticatedFixedCostsRouteChildren: AuthenticatedFixedCostsRouteChildren =
  {
    AuthenticatedFixedCostsReportsRoute: AuthenticatedFixedCostsReportsRoute,
    AuthenticatedFixedCostsIndexRoute: AuthenticatedFixedCostsIndexRoute,
  }

const AuthenticatedFixedCostsRouteWithChildren =
  AuthenticatedFixedCostsRoute._addFileChildren(
    AuthenticatedFixedCostsRouteChildren,
  )

interface AuthenticatedMarketingRouteChildren {
  AuthenticatedMarketingAddRoute: typeof AuthenticatedMarketingAddRoute
  AuthenticatedMarketingReportsRoute: typeof AuthenticatedMarketingReportsRoute
  AuthenticatedMarketingIndexRoute: typeof AuthenticatedMarketingIndexRoute
  AuthenticatedMarketingPlatformIdRoute: typeof AuthenticatedMarketingPlatformIdRoute
}

const AuthenticatedMarketingRouteChildren: AuthenticatedMarketingRouteChildren =
  {
    AuthenticatedMarketingAddRoute: AuthenticatedMarketingAddRoute,
    AuthenticatedMarketingReportsRoute: AuthenticatedMarketingReportsRoute,
    AuthenticatedMarketingIndexRoute: AuthenticatedMarketingIndexRoute,
    AuthenticatedMarketingPlatformIdRoute:
      AuthenticatedMarketingPlatformIdRoute,
  }

const AuthenticatedMarketingRouteWithChildren =
  AuthenticatedMarketingRoute._addFileChildren(
    AuthenticatedMarketingRouteChildren,
  )

interface AuthenticatedReturnsRouteChildren {
  AuthenticatedReturnsIdRoute: typeof AuthenticatedReturnsIdRoute
  AuthenticatedReturnsAddRoute: typeof AuthenticatedReturnsAddRoute
  AuthenticatedReturnsPendingRoute: typeof AuthenticatedReturnsPendingRoute
  AuthenticatedReturnsReportsRoute: typeof AuthenticatedReturnsReportsRoute
  AuthenticatedReturnsIndexRoute: typeof AuthenticatedReturnsIndexRoute
  AuthenticatedReturnsReasonIdRoute: typeof AuthenticatedReturnsReasonIdRoute
}

const AuthenticatedReturnsRouteChildren: AuthenticatedReturnsRouteChildren = {
  AuthenticatedReturnsIdRoute: AuthenticatedReturnsIdRoute,
  AuthenticatedReturnsAddRoute: AuthenticatedReturnsAddRoute,
  AuthenticatedReturnsPendingRoute: AuthenticatedReturnsPendingRoute,
  AuthenticatedReturnsReportsRoute: AuthenticatedReturnsReportsRoute,
  AuthenticatedReturnsIndexRoute: AuthenticatedReturnsIndexRoute,
  AuthenticatedReturnsReasonIdRoute: AuthenticatedReturnsReasonIdRoute,
}

const AuthenticatedReturnsRouteWithChildren =
  AuthenticatedReturnsRoute._addFileChildren(AuthenticatedReturnsRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedBackupRoute: typeof AuthenticatedBackupRoute
  AuthenticatedDamagesRoute: typeof AuthenticatedDamagesRouteWithChildren
  AuthenticatedFixedCostsRoute: typeof AuthenticatedFixedCostsRouteWithChildren
  AuthenticatedLossRoute: typeof AuthenticatedLossRoute
  AuthenticatedMarketingRoute: typeof AuthenticatedMarketingRouteWithChildren
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReadinessRoute: typeof AuthenticatedReadinessRoute
  AuthenticatedReturnsRoute: typeof AuthenticatedReturnsRouteWithChildren
  AuthenticatedSystemRoute: typeof AuthenticatedSystemRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedExpensesIdRoute: typeof AuthenticatedExpensesIdRoute
  AuthenticatedExpensesAddRoute: typeof AuthenticatedExpensesAddRoute
  AuthenticatedExpensesCategoriesRoute: typeof AuthenticatedExpensesCategoriesRoute
  AuthenticatedExpensesPendingRoute: typeof AuthenticatedExpensesPendingRoute
  AuthenticatedExpensesRecycleBinRoute: typeof AuthenticatedExpensesRecycleBinRoute
  AuthenticatedReportsDetailedRoute: typeof AuthenticatedReportsDetailedRoute
  AuthenticatedReportsExportHistoryRoute: typeof AuthenticatedReportsExportHistoryRoute
  AuthenticatedReportsSummaryRoute: typeof AuthenticatedReportsSummaryRoute
  AuthenticatedSettingsCompanyRoute: typeof AuthenticatedSettingsCompanyRoute
  AuthenticatedSettingsFixedCostsRoute: typeof AuthenticatedSettingsFixedCostsRoute
  AuthenticatedSettingsLossRoute: typeof AuthenticatedSettingsLossRoute
  AuthenticatedSettingsMarketingRoute: typeof AuthenticatedSettingsMarketingRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsPermissionsRoute: typeof AuthenticatedSettingsPermissionsRoute
  AuthenticatedSettingsPreferencesRoute: typeof AuthenticatedSettingsPreferencesRoute
  AuthenticatedSettingsSignatoriesRoute: typeof AuthenticatedSettingsSignatoriesRoute
  AuthenticatedExpensesIndexRoute: typeof AuthenticatedExpensesIndexRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedDashboardCategoryIdRoute: typeof AuthenticatedDashboardCategoryIdRoute
  AuthenticatedDashboardSubcategoryIdRoute: typeof AuthenticatedDashboardSubcategoryIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedBackupRoute: AuthenticatedBackupRoute,
  AuthenticatedDamagesRoute: AuthenticatedDamagesRouteWithChildren,
  AuthenticatedFixedCostsRoute: AuthenticatedFixedCostsRouteWithChildren,
  AuthenticatedLossRoute: AuthenticatedLossRoute,
  AuthenticatedMarketingRoute: AuthenticatedMarketingRouteWithChildren,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReadinessRoute: AuthenticatedReadinessRoute,
  AuthenticatedReturnsRoute: AuthenticatedReturnsRouteWithChildren,
  AuthenticatedSystemRoute: AuthenticatedSystemRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedExpensesIdRoute: AuthenticatedExpensesIdRoute,
  AuthenticatedExpensesAddRoute: AuthenticatedExpensesAddRoute,
  AuthenticatedExpensesCategoriesRoute: AuthenticatedExpensesCategoriesRoute,
  AuthenticatedExpensesPendingRoute: AuthenticatedExpensesPendingRoute,
  AuthenticatedExpensesRecycleBinRoute: AuthenticatedExpensesRecycleBinRoute,
  AuthenticatedReportsDetailedRoute: AuthenticatedReportsDetailedRoute,
  AuthenticatedReportsExportHistoryRoute:
    AuthenticatedReportsExportHistoryRoute,
  AuthenticatedReportsSummaryRoute: AuthenticatedReportsSummaryRoute,
  AuthenticatedSettingsCompanyRoute: AuthenticatedSettingsCompanyRoute,
  AuthenticatedSettingsFixedCostsRoute: AuthenticatedSettingsFixedCostsRoute,
  AuthenticatedSettingsLossRoute: AuthenticatedSettingsLossRoute,
  AuthenticatedSettingsMarketingRoute: AuthenticatedSettingsMarketingRoute,
  AuthenticatedSettingsNotificationsRoute:
    AuthenticatedSettingsNotificationsRoute,
  AuthenticatedSettingsPermissionsRoute: AuthenticatedSettingsPermissionsRoute,
  AuthenticatedSettingsPreferencesRoute: AuthenticatedSettingsPreferencesRoute,
  AuthenticatedSettingsSignatoriesRoute: AuthenticatedSettingsSignatoriesRoute,
  AuthenticatedExpensesIndexRoute: AuthenticatedExpensesIndexRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  AuthenticatedDashboardCategoryIdRoute: AuthenticatedDashboardCategoryIdRoute,
  AuthenticatedDashboardSubcategoryIdRoute:
    AuthenticatedDashboardSubcategoryIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  UpdatePasswordRoute: UpdatePasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
